# Generated by Django 4.2.2 on 2023-06-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
                ('startingBid', models.PositiveIntegerField()),
                ('imgURL', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('fshn', 'Fashion'), ('tys', 'Toys'), ('elc', 'Electronics'), ('hom', 'Home'), ('', 'etc')], max_length=4, null=True)),
            ],
        ),
    ]
