# Generated by Django 4.2.2 on 2023-06-20 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_comment_auction_remove_comment_commenter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
                ('startingBid', models.PositiveIntegerField()),
                ('imgURL', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('fshn', 'Fashion'), ('tys', 'Toys'), ('elc', 'Electronics'), ('hom', 'Home'), ('', 'etc')], max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingComments', to='auctions.listing')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingBids', to='auctions.listing')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userBids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
