# Generated by Django 4.2.2 on 2023-06-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('fshn', 'Fashion'), ('tys', 'Toys'), ('elc', 'Electronics'), ('hom', 'Home'), ('', 'N/A')], max_length=4, null=True),
        ),
    ]
