# Generated by Django 4.2.2 on 2023-06-25 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lister',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userListings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
