# Generated by Django 5.1.5 on 2025-09-07 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_tool', '0002_content_doc_content_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='owner',
            new_name='author',
        ),
    ]
