# Generated by Django 5.1.5 on 2025-09-07 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_tool', '0003_rename_owner_doc_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='content_files/'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='root_content_node',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_for_doc', to='authoring_tool.content'),
        ),
    ]
