# Generated by Django 5.1.5 on 2025-09-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_tool', '0004_alter_content_file_alter_doc_root_content_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
