# Generated by Django 5.1.5 on 2025-09-08 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_tool', '0005_alter_doc_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resources/')),
                ('type', models.CharField(choices=[('JS', 'JavaScript'), ('CSS', 'CSS'), ('FONT', 'Font'), ('SVG', 'SVG'), ('HTML', 'HTML')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
