# Generated by Django 5.1.5 on 2025-09-15 13:27

import authoring_tool.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_tool', '0006_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=authoring_tool.models.attachment_upload_path)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('MODEL', 'Interactive Model'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='authoring_tool.content')),
            ],
        ),
    ]
