# Generated by Django 5.1.5 on 2025-09-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_tool', '0007_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
