# Generated by Django 4.1.7 on 2023-08-06 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follower_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='followee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userFollowees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userFollowers', to=settings.AUTH_USER_MODEL),
        ),
    ]
