# Generated by Django 5.1.5 on 2025-04-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_picture',
            new_name='profilePicture',
        ),
    ]
