# Generated by Django 5.1.5 on 2025-07-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_user_is_announcer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_announcer',
        ),
    ]
